# -----------------------------------------------------------------
# MASTER CONFIG for Exercise Video Generation
# -----------------------------------------------------------------

# -- Section 1: Asset Paths --
paths:
  asset_output_dir: 'assets'
  timers_subdir: 'timers'
  # font_file has been moved to the specific sections below.

# -- NEW SECTION: Source Video Processing --
# Defines filters to apply to the main source video (e.g., your GH6 footage)
# This is where you convert V-Log to a standard viewable format.
source_video_processing:
  # Set to true to enable the LUT. Set to false to skip this step entirely.
  apply_lut: true
  
  # The full path to your .cube, .3dl, or other LUT file.
  # Use a LUT designed for your camera's log profile (e.g., V-Log to Rec.709)
  lut_file: 'C:/Users/Preston Connors/Downloads/VLog_to_V709_forV35_EN/VLog_to_V709_forV35_ver100.cube'

# -- Section 2: Progress Ring Style --
progress_ring:
  fps: 60
  direction: 'clockwise'
  size: 400
  stroke_width: 30
  border_width: 3
  no_text: false
  position:
    x: 'W-w-250'
    y: '250'
  text:
    # Font specifically for the countdown number
    font_file: 'C:/Users/Preston Connors/AppData/Local/Microsoft/Windows/Fonts/Inter-VariableFont_opsz,wght.ttf' # Example: A digital-style font
    font_style: 'ExtraBold' # Variable font style for the countdown
    font_size_ratio: 0.4
    stroke_width: 4
    hide_on_zero: true
    background_circle:
      enabled: true
    color: 'black@0.7'  # Same format as the exercise name box
    padding: 0          # Extra radius (in pixels) around the text area


# -- Section 3: Text Overlay Styles --
text_overlays:
  exercise_name:
    # Font specifically for the exercise title card
    font_file: 'C:/Users/Preston Connors/AppData/Local/Microsoft/Windows/Fonts/Roboto-VariableFont_wdth,wght.ttf'
    font_style: 'ExtraBold' # Variable font style for the title
    font_size: 120
    font_color: 'white'
    box_color: 'black@0.7'
    box_border_width: 15
    position_x: '250'
    position_y: '250'
    wrap_at_char: 20
    
    
video_output:
  # --- MODIFIED: Added a new, better option ---
  # 'scale': (Fastest) Resizes the entire source frame, may distort aspect ratio.
  # 'crop':  (Simple) Crops from the center of the source. Only works well if aspect ratios match.
  # 'scale_and_crop': (Best Quality) Scales to fill the height, then crops the width. Perfect for non-16:9 sources.
  framing_method: 'scale_and_crop'
  resolution: '3840x2160'
  codec: 'h264_nvenc'
  preset: 'p6'
  quality: 19
  audio_codec: 'aac'
  audio_bitrate: '192k'
  audio_channels: 2

  # -- NEW SECTION: Test Mode Overrides --
# These settings will be used INSTEAD of the ones in video_output when
# the --test flag is used with assemble_video.py.
test_mode_settings:
  resolution: '854x480'  # 480p SD
  framerate: 15          # Low frame rate for speed
  codec: 'h264_nvenc'
  preset: 'p1'           # Fastest possible preset
  quality: 28            # Lower quality, much faster encode
  audio_bitrate: '96k'   # Lower audio quality for test
  # audio_channels is inherited from video_output if not specified here