# -----------------------------------------------------------------
# MASTER CONFIG for Exercise Video Generation
# -----------------------------------------------------------------

# -- Section 1: Asset Paths --
paths:
  asset_output_dir: 'assets'
  timers_subdir: 'timers'
  # font_file has been moved to the specific sections below.


# -- Section 2: Progress Ring Style --
progress_ring:
  fps: 60
  direction: 'clockwise'
  size: 400
  stroke_width: 30
  border_width: 3
  no_text: false 
  text:
    # Font specifically for the countdown number
    font_file: 'C:/Users/Preston Connors/AppData/Local/Microsoft/Windows/Fonts/Inter-VariableFont_opsz,wght.ttf' # Example: A digital-style font
    font_style: 'Bold' # Variable font style for the countdown
    font_size_ratio: 0.4
    stroke_width: 4
    hide_on_zero: true
    background_circle:
      enabled: true
    color: 'black@0.7'  # Same format as the exercise name box
    padding: 0          # Extra radius (in pixels) around the text area


# -- Section 3: Text Overlay Styles --
text_overlays:
  exercise_name:
    # Font specifically for the exercise title card
    font_file: 'C:/Users/Preston Connors/AppData/Local/Microsoft/Windows/Fonts/Roboto-VariableFont_wdth,wght.ttf'
    font_style: 'Bold' # Variable font style for the title
    font_size: 80
    font_color: 'white'
    box_color: 'black@0.7'
    box_border_width: 15
    position_x: '(w-text_w)/2'
    position_y: 'h*0.8'
    wrap_at_char: 25
    show_for_seconds: 5
    show_from_second: 1
    
    
# -- Section 4: Final Video Output Settings --
video_output:
  resolution: '3840x2160'
  codec: 'h264_nvenc'
  preset: 'p6'
  quality: 19
  audio_codec: 'aac'
  audio_bitrate: '192k'