# -----------------------------------------------------------------
# MASTER CONFIG for Exercise Video Generation
# -----------------------------------------------------------------

# -- Section 1: Asset Paths --
paths:
  asset_output_dir: 'assets'
  timers_subdir: 'timers'
  filter_script_template: 'filter_template.txt'

opencl:
  device: "0.0"   # e.g., NVIDIA CUDA / GeForce RTX 3070 Ti Laptop GPU

# -- Section 2: Source Video Processing --
source_video_processing:
  apply_lut: true
  # NEW: Changed 'lut_file' to 'lut_files' to allow for multiple sequential LUTs.
  # They will be applied in the order they are listed.
  lut_files: 
    - 'luts/VLog_to_V709_forV35_ver100.cube'
    #- 'luts/basic_correction.cube'
    - 'luts/final.cube'
    # - 'C:/path/to/another/creative_lut.cube' # You can add a second LUT here

# -- Section 3: Finishing Filters --
finishing_filters:
  denoise:
    enabled: false
    backend: 'opencl'
    strength: 1.0 
  sharpen:
    enabled: true
    backend: 'cuda'
    luma_amount: 0.5

# -- Section 4: Progress Ring Style --
progress_ring:
  fps: 60
  direction: 'clockwise'
  size: 600
  stroke_width: 30
  border_width: 3
  trail_color: '#696969'
  no_text: false 
  position:
    x: 'W-w-250'
    y: '250'
  text:
    font_file: 'C:/Users/Preston Connors/AppData/Local/Microsoft/Windows/Fonts/Inter-VariableFont_opsz,wght.ttf'
    font_style: 'Bold'
    font_size_ratio: 0.4
    stroke_width: 4
    hide_on_zero: true
    background_circle:
      enabled: true
      color: 'black@0.7'
      padding: 0

# -- Section 5: Text Overlay Styles --
text_overlays:
  exercise_name:
    font_file: 'C:/Users/Preston Connors/AppData/Local/Microsoft/Windows/Fonts/Roboto-VariableFont_wdth,wght.ttf'
    font_style: 'ExtraBold'
    font_size: 180
    font_color: 'white'
    box_color: 'black@0.7'
    box_border_width: 15
    position_x: '250'
    position_y: '250'
    wrap_at_char: 20

# -- Section 6: Sound Effects --
sound_effects:
  master_volume: 0.8
  effects:
    countdown_timer:
      file: 'assets/sounds/interval_4_seconds.wav'
      volume: 0.5
      layout: 'stereo'
  rules:
    - name: 'countdown_timer'
      effect: 'countdown_timer'
      triggers: ['*'] 
      start_time: -4.0
      play_percent: 100

# -- Section 7: Background Music (NEW) --
background_music:
  enabled: true
  master_volume: 0.10      # Lower volume so it doesn't overpower speech
  music_folder: 'assets/music/High Energy' # Folder with your .mp3, .wav, etc. files
  fade_duration: 2.5       # Fade in/out duration for the entire video
  crossfade_duration: 2.5  # NEW: Duration for crossfades between songs
  ducking_enabled: true    # Automatically lower music volume when SFX plays
  ducking_volume: 0.2      # Volume to duck to (20% of original BGM volume)
  rules:
    - name: 'High-Energy Music for Intense Exercise'
      triggers: ['Burpees', 'Jump Squats', 'Kettlebell Swings']
      file: 'assets/music/high_energy_track.mp3'
      mode: 'loop'         # 'loop' for the segment, 'continue' across segments
    - name: 'Calm Music for Rest'
      triggers: ['Cool Down', 'Outro']
      folder: 'assets/music/Calm'
      mode: 'continue'
    - name: 'Intro Music'
      triggers: ['Intro']
      folder: 'assets/music/Intro'
      mode: 'continue'

# -- Section 8: Final Video Output Settings --
video_output:
  bit_depth: 10
  framing_method: 'crop'
  resolution: '3840x2160'
  codec: 'h264_nvenc'
  preset: 'p6'
  quality: 19
  audio_codec: 'aac'
  audio_bitrate: '192k'
  audio_channels: 2

# -- Section 9: Test Mode Overrides --
test_mode_settings:
  resolution: '854x480'
  codec: 'h264_nvenc'
  preset: 'p1'
  quality: 28
  audio_bitrate: '96k'

# -- Section 10: Final Audio Optimization --
audio_optimization:
  enabled: true

  # Stage 1: Applied during segment creation for vocal clarity
  vocal_enhancement:
    enabled: true
    # Cuts low-end mic rumble below this frequency (in Hz)
    highpass_hz: 80
    # Boosts vocal presence at this frequency (in Hz)
    presence_boost_hz: 2500
    # How much to boost the presence (in dB)
    presence_boost_db: 2
    # FFmpeg compand filter string for vocal consistency
    compression_params: "compand=attacks=0:points=-80/-900|-45/-15|-27/-9|-5/-5|20/20"

  # Stage 2: Applied to the final concatenated video for platform compliance
  loudness_normalization:
    enabled: true
    target_i: -16      # Target Integrated Loudness (LUFS)
    target_lra: 11     # Target Loudness Range (LU)
    target_tp: -1.5    # Target True Peak (dBFS)