# ---------------------------------------------------------------------------
# Visual Configuration for the Exercise Routine Video Editor
# ---------------------------------------------------------------------------

# --- Safe Margins ---
safe_margins:
  horizontal_percent: 5
  vertical_percent: 5

# --- Global Font and Color Settings ---
font_file: 'C:/Windows/Fonts/arialbd.ttf'
font_color: 'white'
stroke_color: 'black'

# --- Exercise Name (Top-Left) ---
exercise_name:
  font_file: 'C:/Users/Preston Connors/AppData/Local/Microsoft/Windows/Fonts/Roboto-VariableFont_wdth,wght.ttf'
  position: ['left', 'top']
  font_size: 120
  stroke_width: 2
  # Increased padding for better visual balance and to prevent clipping.
  background_padding_percent: 20

# --- Countdown Timer (Top-Right) ---
countdown_timer:
  font_file: 'C:/Users/Preston Connors/AppData/Local/Microsoft/Windows/Fonts/Inter-VariableFont_opsz,wght.ttf'
  position: ['right', 'top']
  font_size: 120
  stroke_width: 4
  
  # NEW: Percentage to increase the background circle size relative to the text.
  background_padding_percent: 25

  progress_circle:
    width: 10 # The thickness of the progress bar in pixels


# --- Progress Bar (Bottom) ---
# ... (rest of the file is unchanged) ...
progress_bar:
  position: ['center', 'bottom']
  height: 15
  foreground_color: [255, 165, 0, 255] # Orange, RGBA
  background_color: [50, 50, 50, 255]  # Dark Grey, RGBA

# --- "Next Up" Picture-in-Picture (Bottom-Right) ---
next_up_preview:
  position: ['right', 'bottom']
  show_before_end_seconds: 10
  scale: 0.25
  text:
    font_file: 'C:/Users/Preston Connors/AppData/Local/Microsoft/Windows/Fonts/Roboto-VariableFont_wdth,wght.ttf'
    font_size: 30
    stroke_width: 1